### PR TITLE
Add method gets the instance public IP when provider is AWS

### PR DESCRIPTION
**Pull request by aki2o**
I'd like AWS as a provider.
So, I'd added the method and document to get the machine IP for the users like me.
If bad manner or strange expression is in my updates, point out without hesitation.
Thanks.

### CODE REVIEW

**Comment by cgsmith** [comment]
I am going to test this PR out locally to see if it can be brought in.

**Comment by andreyev** [comment]
+1

**Comment by davidfsmith** [comment]
+1

**Comment by cgsmith** [comment]
Pulled into `develop` with this aa21ffcad911e310a4b0a3f0c96617c72cabafbc

Thanks @aki2o !

**Comment by kentr** [comment]
@cgsmith Any chance of getting this into the stable branch?

**Pull request closed without merging**
