### PR TITLE
Added support for multiple private_network adapters

### PR DESCRIPTION
**Pull request by maximerety**
New PR for feature request https://github.com/cogitatio/vagrant-hostsupdater/issues/58

### CODE REVIEW

**Comment by cgsmith** [comment]
Thanks for the PR @maximerety!

I will review this next week and get it merged in :)

**Comment by denschu** [comment]
Great feature! Is there a planned release date already? :-)

**Comment by cgsmith** [comment]
Within two weeks @denschu

Feel free to checkout develop and test it out as well.

**Comment by moltar** [comment]
Has this been released yet?

**Pull request merged**
